resolver: lts-20.16

extra-deps:
  - url: https://github.com/llvm-hs/llvm-hs/archive/refs/heads/llvm-15.zip
    subdirs:
      - llvm-hs
      - llvm-hs-pure

extra-include-dirs:
  - /opt/homebrew/include/

extra-lib-dirs:
  - /opt/homebrew/lib/
